import { Listing } from "./types";

export const categories = [
  "All items",
  "Textbooks",
  "Furniture",
  "Tech",
  "Fashion",
];

export const seedListings: Listing[] = [
  {
    id: "1",
    title: "Calculus: Early Transcendentals",
    price: 35,
    category: "Textbooks",
    seller: "Maya R.",
    campus: "North Campus",
    condition: "Like new",
    image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=800",
    description: "Barely used and ready for your next math class.",
    status: "available",
  },
  {
    id: "2",
    title: "Walnut study desk",
    price: 80,
    category: "Furniture",
    seller: "Jordan K.",
    campus: "West Village",
    condition: "Good condition",
    image: "https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=800",
    description: "Solid walnut desk with room for a monitor and books.",
    status: "available",
  },
  {
    id: "3",
    title: "Noise-cancelling headphones",
    price: 120,
    category: "Tech",
    seller: "Alex P.",
    campus: "East Quad",
    condition: "Like new",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800",
    description: "Wireless headphones with case and charging cable.",
    status: "available",
  },
  {
    id: "4",
    title: "Vintage varsity jacket",
    price: 45,
    category: "Fashion",
    seller: "Sam T.",
    campus: "North Campus",
    condition: "Good condition",
    image: "https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?w=800",
    description: "A warm, classic layer with a relaxed fit.",
    status: "available",
  },
  {
    id: "5",
    title: "Introduction to Psychology",
    price: 28,
    category: "Textbooks",
    seller: "Nimal S.",
    campus: "South Campus",
    condition: "Good condition",
    image: "https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=800",
    description: "Latest edition with a few highlighted chapters.",
    status: "available",
  },
  {
    id: "6",
    title: "Ergonomic office chair",
    price: 65,
    category: "Furniture",
    seller: "Ayesha M.",
    campus: "West Village",
    condition: "Like new",
    image: "https://images.unsplash.com/photo-1505797149-35ebcb05a6fd?w=800",
    description: "Comfortable adjustable chair, ideal for long study sessions.",
    status: "available",
  },
  {
    id: "7",
    title: "Mechanical keyboard",
    price: 55,
    category: "Tech",
    seller: "Kevin D.",
    campus: "East Quad",
    condition: "Like new",
    image: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800",
    description: "Compact wireless keyboard with quiet tactile switches.",
    status: "available",
  },
  {
    id: "8",
    title: "Canvas backpack",
    price: 22,
    category: "Fashion",
    seller: "Sara L.",
    campus: "North Campus",
    condition: "Good condition",
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800",
    description: "Spacious everyday backpack with a padded laptop sleeve.",
    status: "available",
  },
  {
    id: "9",
    title: "Data Structures and Algorithms",
    price: 40,
    category: "Textbooks",
    seller: "Ishan P.",
    campus: "Central Campus",
    condition: "Like new",
    image: "https://images.unsplash.com/photo-1532012197267-da84d127e765?w=800",
    description: "Clean copy with useful notes included on separate pages.",
    status: "available",
  },
  {
    id: "10",
    title: "Bedside table",
    price: 30,
    category: "Furniture",
    seller: "Priya K.",
    campus: "South Campus",
    condition: "Good condition",
    image: "https://images.unsplash.com/photo-1532372320572-cda25653a694?w=800",
    description: "Small wooden table with one drawer and an open shelf.",
    status: "available",
  },
  {
    id: "11",
    title: "Portable Bluetooth speaker",
    price: 38,
    category: "Tech",
    seller: "Daniel J.",
    campus: "West Village",
    condition: "Good condition",
    image: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=800",
    description: "Compact waterproof speaker with charging cable included.",
    status: "available",
  },
  {
    id: "12",
    title: "Classic denim jacket",
    price: 32,
    category: "Fashion",
    seller: "Lina F.",
    campus: "East Quad",
    condition: "Like new",
    image: "https://images.unsplash.com/photo-1542272604-787c3835535d?w=800",
    description: "Medium-size denim jacket worn only a few times.",
    status: "available",
  },
  {
    id: "13",
    title: "Scientific calculator",
    price: 18,
    category: "Tech",
    seller: "Omar H.",
    campus: "Central Campus",
    condition: "Good condition",
    image: "https://images.unsplash.com/photo-1574607383476-f517f260d30b?w=800",
    description: "Reliable calculator suitable for engineering and science courses.",
    status: "available",
  },
  {
    id: "14",
    title: "Adjustable desk lamp",
    price: 20,
    category: "Furniture",
    seller: "Chloe W.",
    campus: "North Campus",
    condition: "Like new",
    image: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800",
    description: "Bright LED study lamp with adjustable arm and three light modes.",
    status: "available",
  },
];
